# Generated by Django 4.2.9 on 2024-04-08 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
    ]
