# Generated by Django 4.2.9 on 2024-04-08 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_document_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="uploaded_file",
            new_name="document",
        ),
    ]
