# Generated by Django 4.2.9 on 2024-04-08 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_rename_uploaded_file_document_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="document",
            new_name="upload_file",
        ),
    ]
